version: "3.2"
services:
    frontend:
        image: crypto-client
        environment: 
        -   NODE_ENV=development
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports: 
        -   4200:4200
        #network_mode: host
        networks: 
        -   frontend-net
        depends_on: 
        -   backend
        restart: on-failure
    backend:
        image: crypto-server 
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
        -   3001:3000
        networks:
        -   backend-net
        links: 
        -   db
        restart: on-failure
    db:
        image: mongo
        #environment: 
        #-   MONGO_INIT_ROOT_USERNAME='root'
        #-   MONGO_INIT_ROOT_PASSWORD='root'
        ports: 
        -   27017:27017
        networks:
        -   backend-net
        -   mongo-express-net
        volumes: 
        -   ./database/db:/data/db
    mongo-frontend:
        image: mongo-express
        environment: 
        -   ME_CONFIG_MONGODB_SERVER=db
        #-   ME_CONFIG_MONGODB_AUTH_USERNAME='root'
        #-   ME_CONFIG_MONGODB_AUTH_PASSWORD='root'
        ports: 
        -   8081:8081
        links: 
        -   db
        networks:
        -   mongo-express-net
        restart: on-failure
networks:
    frontend-net:
        driver: bridge
    backend-net:
        driver: bridge
    mongo-express-net:
        driver: bridge
volumes: 
    database-vol:
